-- Prova Social backend v1: social graph, library and trustworthy attempts.

alter table public.exams
  add column if not exists source_type text not null default 'community'
    check (source_type in ('official', 'community', 'unverified')),
  add column if not exists source_url text
    check (source_url is null or char_length(source_url) <= 500);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  name text not null unique check (char_length(name) between 2 and 80),
  created_at timestamptz not null default now()
);

create table if not exists public.exam_topics (
  exam_id uuid not null references public.exams(id) on delete cascade,
  topic_id bigint not null references public.topics(id) on delete cascade,
  primary key (exam_id, topic_id)
);

create table if not exists public.topic_follows (
  user_id uuid not null references public.profiles(id) on delete cascade,
  topic_id bigint not null references public.topics(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, topic_id)
);

create table if not exists public.collections (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 2 and 100),
  description text not null default '' check (char_length(description) <= 500),
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.collection_exams (
  collection_id uuid not null references public.collections(id) on delete cascade,
  exam_id uuid not null references public.exams(id) on delete cascade,
  position integer not null default 1 check (position > 0),
  added_at timestamptz not null default now(),
  primary key (collection_id, exam_id)
);

create table if not exists public.profile_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followed_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, followed_id),
  check (follower_id <> followed_id)
);

create table if not exists public.question_comments (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.questions(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  parent_id uuid references public.question_comments(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  status text not null default 'visible' check (status in ('visible', 'hidden', 'deleted')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comment_votes (
  comment_id uuid not null references public.question_comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

create index if not exists exam_topics_topic_id_idx on public.exam_topics(topic_id);
create index if not exists topic_follows_topic_id_idx on public.topic_follows(topic_id);
create index if not exists collections_owner_id_idx on public.collections(owner_id);
create index if not exists collection_exams_exam_id_idx on public.collection_exams(exam_id);
create index if not exists profile_follows_followed_id_idx on public.profile_follows(followed_id);
create index if not exists question_comments_question_created_idx on public.question_comments(question_id, created_at);
create index if not exists question_comments_author_id_idx on public.question_comments(author_id);
create index if not exists question_comments_parent_id_idx on public.question_comments(parent_id);
create index if not exists comment_votes_user_id_idx on public.comment_votes(user_id);

alter table public.topics enable row level security;
alter table public.exam_topics enable row level security;
alter table public.topic_follows enable row level security;
alter table public.collections enable row level security;
alter table public.collection_exams enable row level security;
alter table public.profile_follows enable row level security;
alter table public.question_comments enable row level security;
alter table public.comment_votes enable row level security;

create policy topics_public_read on public.topics for select to anon, authenticated using (true);
create policy exam_topics_public_read on public.exam_topics for select to anon, authenticated using (
  exists (select 1 from public.exams e where e.id = exam_id and ((e.status = 'published' and e.is_public) or e.author_id = (select auth.uid())))
);
create policy topic_follows_owner_read on public.topic_follows for select to authenticated using ((select auth.uid()) = user_id);
create policy topic_follows_owner_insert on public.topic_follows for insert to authenticated with check ((select auth.uid()) = user_id);
create policy topic_follows_owner_delete on public.topic_follows for delete to authenticated using ((select auth.uid()) = user_id);

create policy collections_read on public.collections for select to anon, authenticated using (is_public or owner_id = (select auth.uid()));
create policy collections_owner_insert on public.collections for insert to authenticated with check (owner_id = (select auth.uid()));
create policy collections_owner_update on public.collections for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy collections_owner_delete on public.collections for delete to authenticated using (owner_id = (select auth.uid()));
create policy collection_exams_read on public.collection_exams for select to anon, authenticated using (
  exists (select 1 from public.collections c where c.id = collection_id and (c.is_public or c.owner_id = (select auth.uid())))
);
create policy collection_exams_owner_insert on public.collection_exams for insert to authenticated with check (
  exists (select 1 from public.collections c where c.id = collection_id and c.owner_id = (select auth.uid()))
);
create policy collection_exams_owner_update on public.collection_exams for update to authenticated using (
  exists (select 1 from public.collections c where c.id = collection_id and c.owner_id = (select auth.uid()))
) with check (
  exists (select 1 from public.collections c where c.id = collection_id and c.owner_id = (select auth.uid()))
);
create policy collection_exams_owner_delete on public.collection_exams for delete to authenticated using (
  exists (select 1 from public.collections c where c.id = collection_id and c.owner_id = (select auth.uid()))
);

create policy profile_follows_public_read on public.profile_follows for select to anon, authenticated using (true);
create policy profile_follows_owner_insert on public.profile_follows for insert to authenticated with check (follower_id = (select auth.uid()));
create policy profile_follows_owner_delete on public.profile_follows for delete to authenticated using (follower_id = (select auth.uid()));

create policy question_comments_public_read on public.question_comments for select to anon, authenticated using (
  status = 'visible' and exists (
    select 1 from public.questions q join public.exams e on e.id = q.exam_id
    where q.id = question_id and e.status = 'published' and e.is_public
  )
);
create policy question_comments_owner_insert on public.question_comments for insert to authenticated with check (
  author_id = (select auth.uid()) and status = 'visible'
);
create policy question_comments_owner_update on public.question_comments for update to authenticated using (
  author_id = (select auth.uid())
) with check (author_id = (select auth.uid()) and status in ('visible', 'deleted'));
create policy question_comments_owner_delete on public.question_comments for delete to authenticated using (author_id = (select auth.uid()));
create policy comment_votes_public_read on public.comment_votes for select to anon, authenticated using (true);
create policy comment_votes_owner_insert on public.comment_votes for insert to authenticated with check (user_id = (select auth.uid()));
create policy comment_votes_owner_delete on public.comment_votes for delete to authenticated using (user_id = (select auth.uid()));

-- The public app can read the question, but not its answer key.
revoke select on public.questions from anon, authenticated;
grant select (id, exam_id, position, topic, statement, options, created_at) on public.questions to anon, authenticated;
grant insert on public.attempts, public.attempt_answers to authenticated;

grant select on public.topics, public.exam_topics, public.collections, public.collection_exams,
  public.profile_follows, public.question_comments, public.comment_votes to anon, authenticated;
grant insert, update, delete on public.collections, public.collection_exams, public.question_comments to authenticated;
grant insert, delete on public.topic_follows, public.profile_follows, public.comment_votes to authenticated;
grant usage, select on sequence public.topics_id_seq to authenticated;

insert into public.topics (slug, name) values
  ('enem', 'ENEM'),
  ('pm-sp', 'PM-SP'),
  ('vunesp', 'VUNESP'),
  ('matematica', 'Matemática'),
  ('portugues', 'Português'),
  ('historia', 'História')
on conflict (slug) do update set name = excluded.name;
