name: prova_social
description: Plataforma social para encontrar, resolver e compartilhar provas.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/app_icon.png
  adaptive_icon_background: "#16A36A"
  adaptive_icon_foreground: assets/branding/app_icon.png
  min_sdk_android: 21
